print("hello world")
print(2+3)
print(2-3)
print(4*5)
print(6/3)
print(3**2)
print(3%2)
print(type(10))
print(type(3.14))
print(type(1+3j))
print(type('khoi'))
print(type([1,2,3]))
print("abtraction: ", 2+3)
print("subtraction: ", 4-3)
print("multiplication: ", 5*6)
print("division: ", 5/1)
print("modulus: ", 5%3)
print("exponential: ", 3**2)
print("multiplying complex number: ", (1+1j)*(1-1j))
r=int(input("nhap ban kinh: "))
dien_tich=3.14*(r**2)
print ("dien tich hinh tron la: ", dien_tich)
